---
- name: ePMP Linktest - Fake Tower
  hosts: lab_cambium
#  strategy: linear
  gather_facts: false
  vars:

  tasks:
    - name: Run Linktest for "Fake Customer - 1"
      raw: linktest 00:04:56:60:f8:53 -t 10 -s 1500

    - name: Pause for 10 seconds (to let Linktest finish)
      ansible.builtin.pause:
        seconds: 10

    - name: Use SNMPGET to Retrieve Download Speed
      local_action: command snmpget -v 1 -c fuck 192.168.1.74 .1.3.6.1.4.1.17713.21.6.1.7.0
      register: response

    - name: Print Download Speed for "Fake Customer - 1"
      debug:
        var: response.stdout

    - name: Use SNMPGET to Retrieve Upload Speed
      local_action: command snmpget -v 1 -c fuck 192.168.1.74 .1.3.6.1.4.1.17713.21.6.1.6.0
      register: response

    - name: Print Upload Speed for "Fake Customer - 1"
      debug:
        var: response.stdout
